version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: api-g-cram
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      default:
        aliases:
          - api
  compressor:
    build:
      context: .
      dockerfile: cramer/Dockerfile
    container_name: cramer-g-cram
    environment:
      - LOG_LEVEL=info
    #restart: unless-stopped
    volumes:
      - ./media/in:/tmp/in
      - ./media/out:/tmp/out
    networks:
      default:
        aliases:
          - cramer
  nginx:
    image: nginx:latest
    container_name: front-g-cram
    ports:
      - "8080:80"
    volumes:
      - ./front:/usr/share/nginx/html:ro             # Mount /front directory as web root
    restart: always
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1

configs:
  nginx_config:
    file: ./nginx.conf

