// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearUserTmpMedia(ctx context.Context, userID string) error
	CountUserMedia(ctx context.Context, userID string) (int64, error)
	CountUserMediaInJob(ctx context.Context, arg CountUserMediaInJobParams) (int64, error)
	CountUserMediaInJobAtStep(ctx context.Context, arg CountUserMediaInJobAtStepParams) (int64, error)
	CreateJob(ctx context.Context, userID string) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetJobSpace(ctx context.Context, arg GetJobSpaceParams) (GetJobSpaceRow, error)
	GetMedia(ctx context.Context, arg GetMediaParams) (Medium, error)
	GetMediaCurrentStep(ctx context.Context, arg GetMediaCurrentStepParams) (int64, error)
	GetMedias(ctx context.Context, userID string) ([]Medium, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByTokenHash(ctx context.Context, tokenHash sql.NullString) (User, error)
	GetUserJob(ctx context.Context, userID string) ([]GetUserJobRow, error)
	GetUserJobDetails(ctx context.Context, userID string) ([]GetUserJobDetailsRow, error)
	RemoveMedia(ctx context.Context, mediaID string) error
	SetMediaDone(ctx context.Context, arg SetMediaDoneParams) error
	SetMediaNewSize(ctx context.Context, arg SetMediaNewSizeParams) error
	SetMediaOldSize(ctx context.Context, arg SetMediaOldSizeParams) error
	SetMediaStep(ctx context.Context, arg SetMediaStepParams) error
	SetMediaTimestamp(ctx context.Context, arg SetMediaTimestampParams) error
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error
}

var _ Querier = (*Queries)(nil)
