// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearUserTmpMedia(ctx context.Context, userID string) error
	CountUserMedia(ctx context.Context, userID string) (int64, error)
	CreateJob(ctx context.Context, userID string) error
	CreateMedia(ctx context.Context, arg CreateMediaParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetMedias(ctx context.Context, arg GetMediasParams) ([]Medium, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByTokenHash(ctx context.Context, tokenHash sql.NullString) (User, error)
	GetUserJobDetails(ctx context.Context, userID string) ([]GetUserJobDetailsRow, error)
	RemoveMedia(ctx context.Context, mediaID string) error
	SetMediaDone(ctx context.Context, arg SetMediaDoneParams) error
	SetMediaTimestamp(ctx context.Context, arg SetMediaTimestampParams) error
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
	UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error
}

var _ Querier = (*Queries)(nil)
